def naruto():
    print(" /\/             ")
    print("      _______")
    print("     / /   \ \ ")
    print("    / /     \ \ ")
    print("   | |       | |")
    print("   | |       | |")
    print("   | |       | |")
    print("   | |       | |")
    print("   | |       | |")
    print("   | |       | |")
    print("   | |       | |")
    print("   | |       | |")
    print("   | |       | |")
    print("   | |       | |")
    print("   | |       | |")
    print("   | |       | |")
    print("   | |       | |")
    print("   / |       | \ ")
    print("   | |       | |")
    print("   | |       | |")
    print("   | |       | |")
    print("   | |       | |")
    print("   | |       | |")
    print("  /__\       /__\\")

naruto()